spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <github-client-id>
            client-secret: <github-client-secret>

datastax.astra:
  secure-connect-bundle: connect.zip

astra:
  db:
    id: <astra-db-id>
    region: <astra-db-region>
    keyspace: <astra-db-keyspace-name>
    application:
      token: <astra-app-token>
